//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StepUpDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TraineeInformation
    {
        public int PSnumber { get; set; }
        public string EmailID { get; set; }
        public string CurrentSkillSet { get; set; }
        public string ExpectedTraining_Phase1 { get; set; }
        public string ExpectedTraining_Phase2 { get; set; }
        public System.DateTime Date { get; set; }
    }
}
